[2025-02-15T08:12:34.472+0000] {processor.py:186} INFO - Started process (PID=208) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:12:34.506+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:12:34.528+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:12:34.528+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:12:34.639+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:12:34.763+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:12:34.763+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:12:35.080+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:12:35.079+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-02 03:00:00+00:00, run_after=2025-02-02 06:00:00+00:00
[2025-02-15T08:12:35.431+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.975 seconds
[2025-02-15T08:13:20.504+0000] {processor.py:186} INFO - Started process (PID=570) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:13:20.517+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:13:20.532+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:13:20.531+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:13:20.652+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:13:20.815+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:13:20.815+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:13:21.090+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:13:21.089+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-04 15:00:00+00:00, run_after=2025-02-04 18:00:00+00:00
[2025-02-15T08:13:21.246+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.762 seconds
[2025-02-15T08:14:00.965+0000] {processor.py:186} INFO - Started process (PID=847) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:14:00.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:14:00.975+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:14:00.975+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:14:01.003+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:14:01.067+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:14:01.066+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:14:01.153+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:14:01.152+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-07 09:00:00+00:00, run_after=2025-02-07 12:00:00+00:00
[2025-02-15T08:14:01.197+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.263 seconds
[2025-02-15T08:14:36.870+0000] {processor.py:186} INFO - Started process (PID=1213) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:14:36.891+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:14:36.900+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:14:36.900+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:14:36.967+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:14:37.100+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:14:37.099+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:14:37.236+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:14:37.235+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-10 18:00:00+00:00, run_after=2025-02-10 21:00:00+00:00
[2025-02-15T08:14:37.415+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.562 seconds
[2025-02-15T08:15:08.160+0000] {processor.py:186} INFO - Started process (PID=1588) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:15:08.162+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:15:08.168+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:15:08.167+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:15:08.196+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:15:08.248+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:15:08.247+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:15:08.356+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:15:08.333+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-13 18:00:00+00:00, run_after=2025-02-13 21:00:00+00:00
[2025-02-15T08:15:08.475+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.321 seconds
[2025-02-15T08:15:39.551+0000] {processor.py:186} INFO - Started process (PID=1951) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:15:39.551+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:15:39.554+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:15:39.554+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:15:39.563+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:15:39.585+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:15:39.585+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:15:39.636+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:15:39.635+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:15:39.660+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.115 seconds
[2025-02-15T08:16:00.773+0000] {processor.py:186} INFO - Started process (PID=2184) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:00.774+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:16:00.776+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:16:00.776+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:00.787+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:00.807+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:16:00.807+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:16:00.834+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:16:00.834+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:16:00.856+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.089 seconds
[2025-02-15T08:16:03.026+0000] {processor.py:186} INFO - Started process (PID=2206) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:03.027+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:16:03.029+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:16:03.029+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:03.041+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:03.061+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:16:03.061+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:16:03.088+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:16:03.088+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:16:03.106+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.086 seconds
[2025-02-15T08:16:13.532+0000] {processor.py:186} INFO - Started process (PID=2303) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:13.533+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:16:13.536+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:16:13.535+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:13.544+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:16:13.538+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def
       ^
SyntaxError: invalid syntax
[2025-02-15T08:16:13.545+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:13.571+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.045 seconds
[2025-02-15T08:16:20.955+0000] {processor.py:186} INFO - Started process (PID=2338) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:20.956+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:16:20.958+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:16:20.957+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:20.968+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:16:20.964+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47, in <module>
    def_validation
NameError: name 'def_validation' is not defined
[2025-02-15T08:16:20.971+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:20.985+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.034 seconds
[2025-02-15T08:16:27.393+0000] {processor.py:186} INFO - Started process (PID=2388) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:27.394+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:16:27.397+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:16:27.396+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:27.415+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:16:27.409+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47, in <module>
    def_validate
NameError: name 'def_validate' is not defined
[2025-02-15T08:16:27.421+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:27.470+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.083 seconds
[2025-02-15T08:16:27.698+0000] {processor.py:186} INFO - Started process (PID=2406) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:27.707+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:16:27.713+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:16:27.713+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:27.743+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:16:27.735+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47, in <module>
    def_validate_
NameError: name 'def_validate_' is not defined
[2025-02-15T08:16:27.749+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:27.765+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.083 seconds
[2025-02-15T08:16:33.226+0000] {processor.py:186} INFO - Started process (PID=2533) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:33.227+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:16:33.229+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:16:33.229+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:33.243+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:16:33.238+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47, in <module>
    def_validate_temperature
NameError: name 'def_validate_temperature' is not defined
[2025-02-15T08:16:33.248+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:33.270+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.049 seconds
[2025-02-15T08:16:37.542+0000] {processor.py:186} INFO - Started process (PID=2569) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:37.542+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:16:37.544+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:16:37.544+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:37.553+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:16:37.551+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47, in <module>
    def_validate_temperature_rang
NameError: name 'def_validate_temperature_rang' is not defined
[2025-02-15T08:16:37.554+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:37.569+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.032 seconds
[2025-02-15T08:16:42.683+0000] {processor.py:186} INFO - Started process (PID=2629) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:42.684+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:16:42.686+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:16:42.686+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:42.699+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:16:42.695+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47, in <module>
    def_validate_temperature_
NameError: name 'def_validate_temperature_' is not defined
[2025-02-15T08:16:42.703+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:16:42.722+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.044 seconds
[2025-02-15T08:17:13.085+0000] {processor.py:186} INFO - Started process (PID=2936) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:17:13.086+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:17:13.089+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:17:13.088+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:17:13.101+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:17:13.097+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47, in <module>
    def_validate_temperature_
NameError: name 'def_validate_temperature_' is not defined
[2025-02-15T08:17:13.105+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:17:13.125+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.045 seconds
[2025-02-15T08:17:34.668+0000] {processor.py:186} INFO - Started process (PID=3099) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:17:34.669+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:17:34.670+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:17:34.670+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:17:34.681+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:17:34.679+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47, in <module>
    def_validate_temperature_rang
NameError: name 'def_validate_temperature_rang' is not defined
[2025-02-15T08:17:34.683+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:17:34.702+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.041 seconds
[2025-02-15T08:17:38.610+0000] {processor.py:186} INFO - Started process (PID=3192) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:17:38.611+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:17:38.612+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:17:38.611+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:17:38.619+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:17:38.618+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47, in <module>
    def_validate_temperature_rangeZ
NameError: name 'def_validate_temperature_rangeZ' is not defined
[2025-02-15T08:17:38.620+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:17:38.633+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.028 seconds
[2025-02-15T08:17:39.627+0000] {processor.py:186} INFO - Started process (PID=3197) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:17:39.628+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:17:39.629+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:17:39.628+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:17:39.641+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:17:39.638+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47, in <module>
    def_validate_temperature_range
NameError: name 'def_validate_temperature_range' is not defined
[2025-02-15T08:17:39.643+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:17:39.664+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.043 seconds
[2025-02-15T08:17:40.765+0000] {processor.py:186} INFO - Started process (PID=3212) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:17:40.766+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:17:40.767+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:17:40.767+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:17:40.778+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:17:40.776+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47, in <module>
    def_validate_temperature_range()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'def_validate_temperature_range' is not defined
[2025-02-15T08:17:40.780+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:17:40.802+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.042 seconds
[2025-02-15T08:17:44.777+0000] {processor.py:186} INFO - Started process (PID=3267) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:17:44.777+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:17:44.779+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:17:44.778+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:17:44.790+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:17:44.787+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47, in <module>
    def_validate_temperature_range()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'def_validate_temperature_range' is not defined
[2025-02-15T08:17:44.792+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:17:44.810+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.039 seconds
[2025-02-15T08:17:45.954+0000] {processor.py:186} INFO - Started process (PID=3287) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:17:45.955+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:17:45.956+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:17:45.955+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:17:45.959+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:17:45.958+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def_validate_temperature_range():
                                    ^
SyntaxError: invalid syntax
[2025-02-15T08:17:45.963+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:17:45.983+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.034 seconds
[2025-02-15T08:18:16.406+0000] {processor.py:186} INFO - Started process (PID=3593) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:18:16.409+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:18:16.411+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:18:16.410+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:18:16.424+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:18:16.423+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def_validate_temperature_range():
                                    ^
SyntaxError: invalid syntax
[2025-02-15T08:18:16.428+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:18:16.447+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.046 seconds
[2025-02-15T08:18:46.775+0000] {processor.py:186} INFO - Started process (PID=3898) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:18:46.777+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:18:46.778+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:18:46.777+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:18:46.781+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:18:46.780+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def_validate_temperature_range():
                                    ^
SyntaxError: invalid syntax
[2025-02-15T08:18:46.782+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:18:46.801+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.032 seconds
[2025-02-15T08:19:17.146+0000] {processor.py:186} INFO - Started process (PID=4205) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:19:17.147+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:19:17.150+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:19:17.149+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:19:17.153+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:19:17.153+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def_validate_temperature_range():
                                    ^
SyntaxError: invalid syntax
[2025-02-15T08:19:17.154+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:19:17.173+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.033 seconds
[2025-02-15T08:19:41.674+0000] {processor.py:186} INFO - Started process (PID=4437) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:19:41.675+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:19:41.676+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:19:41.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:19:41.679+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:19:41.678+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:19:41.680+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:19:41.693+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.025 seconds
[2025-02-15T08:20:11.969+0000] {processor.py:186} INFO - Started process (PID=4743) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:20:11.970+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:20:11.971+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:20:11.971+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:20:11.975+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:20:11.974+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:20:11.975+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:20:11.994+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.031 seconds
[2025-02-15T08:20:42.325+0000] {processor.py:186} INFO - Started process (PID=4956) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:20:42.326+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:20:42.327+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:20:42.327+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:20:42.331+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:20:42.330+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:20:42.332+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:20:42.349+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.031 seconds
[2025-02-15T08:21:12.877+0000] {processor.py:186} INFO - Started process (PID=5240) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:21:12.878+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:21:12.879+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:21:12.879+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:21:12.881+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:21:12.881+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:21:12.882+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:21:12.895+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.022 seconds
[2025-02-15T08:21:14.502+0000] {processor.py:186} INFO - Started process (PID=5360) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:21:14.503+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:21:14.504+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:21:14.503+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:21:14.517+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:21:14.656+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:21:14.656+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:21:14.683+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:21:14.683+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:21:14.703+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.207 seconds
[2025-02-15T08:21:28.042+0000] {processor.py:186} INFO - Started process (PID=5455) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:21:28.043+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:21:28.044+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:21:28.044+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:21:28.057+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:21:28.069+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:21:28.069+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:21:28.096+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:21:28.096+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:21:28.117+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.080 seconds
[2025-02-15T08:21:31.063+0000] {processor.py:186} INFO - Started process (PID=5460) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:21:31.064+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:21:31.065+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:21:31.065+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:21:31.074+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:21:31.083+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:21:31.083+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:21:31.101+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:21:31.101+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:21:31.115+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.056 seconds
[2025-02-15T08:22:01.595+0000] {processor.py:186} INFO - Started process (PID=5767) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:22:01.596+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:22:01.597+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:22:01.596+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:22:01.604+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:22:01.620+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:22:01.619+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:22:01.638+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:22:01.637+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:22:01.650+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.060 seconds
[2025-02-15T08:22:19.796+0000] {processor.py:186} INFO - Started process (PID=6034) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:22:19.797+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:22:19.798+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:22:19.798+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:22:19.802+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:22:19.801+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def_validate_temperature_range():
                                    ^
SyntaxError: invalid syntax
[2025-02-15T08:22:19.803+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:22:19.823+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.032 seconds
[2025-02-15T08:22:40.422+0000] {processor.py:186} INFO - Started process (PID=6086) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:22:40.423+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:22:40.424+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:22:40.424+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:22:40.427+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:22:40.426+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 1
    mport json
          ^^^^
SyntaxError: invalid syntax
[2025-02-15T08:22:40.427+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:22:40.441+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.024 seconds
[2025-02-15T08:22:47.688+0000] {processor.py:186} INFO - Started process (PID=6221) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:22:47.689+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:22:47.690+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:22:47.690+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:22:47.694+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:22:47.693+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 46
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:22:47.695+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:22:47.717+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.035 seconds
[2025-02-15T08:23:02.227+0000] {processor.py:186} INFO - Started process (PID=6391) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:23:02.227+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:23:02.228+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:23:02.228+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:23:02.231+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:23:02.230+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:23:02.231+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:23:02.245+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.022 seconds
[2025-02-15T08:23:32.532+0000] {processor.py:186} INFO - Started process (PID=6698) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:23:32.533+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:23:32.534+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:23:32.533+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:23:32.536+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:23:32.535+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:23:32.537+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:23:32.550+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.022 seconds
[2025-02-15T08:24:02.063+0000] {processor.py:186} INFO - Started process (PID=7005) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:02.064+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:24:02.065+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:24:02.065+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:02.067+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:24:02.067+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:24:02.068+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:02.082+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.023 seconds
[2025-02-15T08:24:04.079+0000] {processor.py:186} INFO - Started process (PID=7010) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:04.080+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:24:04.080+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:24:04.080+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:04.083+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:24:04.082+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:24:04.084+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:04.097+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.023 seconds
[2025-02-15T08:24:09.139+0000] {processor.py:186} INFO - Started process (PID=7022) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:09.140+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:24:09.141+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:24:09.140+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:09.143+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:24:09.143+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:24:09.144+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:09.160+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.026 seconds
[2025-02-15T08:24:14.179+0000] {processor.py:186} INFO - Started process (PID=7027) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:14.180+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:24:14.181+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:24:14.181+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:14.183+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:24:14.183+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:24:14.184+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:14.199+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.025 seconds
[2025-02-15T08:24:16.219+0000] {processor.py:186} INFO - Started process (PID=7032) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:16.220+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:24:16.221+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:24:16.221+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:16.224+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:24:16.223+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:24:16.225+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:16.243+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.029 seconds
[2025-02-15T08:24:46.763+0000] {processor.py:186} INFO - Started process (PID=7338) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:46.764+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:24:46.765+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:24:46.765+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:46.768+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:24:46.767+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:24:46.768+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:46.782+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.023 seconds
[2025-02-15T08:24:56.956+0000] {processor.py:186} INFO - Started process (PID=7638) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:56.957+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:24:56.958+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:24:56.957+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:56.960+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:24:56.960+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:24:56.961+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:56.975+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.023 seconds
[2025-02-15T08:24:58.975+0000] {processor.py:186} INFO - Started process (PID=7643) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:58.976+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:24:58.977+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:24:58.977+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:58.980+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:24:58.979+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:24:58.981+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:24:59.003+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.035 seconds
[2025-02-15T08:25:03.037+0000] {processor.py:186} INFO - Started process (PID=7648) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:25:03.038+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:25:03.038+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:25:03.038+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:25:03.041+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:25:03.041+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:25:03.042+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:25:03.055+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.023 seconds
[2025-02-15T08:25:11.083+0000] {processor.py:186} INFO - Started process (PID=7660) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:25:11.083+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:25:11.084+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:25:11.084+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:25:11.087+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:25:11.086+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:25:11.087+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:25:11.102+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.023 seconds
[2025-02-15T08:25:17.167+0000] {processor.py:186} INFO - Started process (PID=7665) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:25:17.168+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:25:17.169+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:25:17.169+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:25:17.173+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:25:17.172+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:25:17.173+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:25:17.191+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.029 seconds
[2025-02-15T08:25:20.302+0000] {processor.py:186} INFO - Started process (PID=7698) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:25:20.303+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:25:20.304+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:25:20.304+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:25:20.307+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:25:20.306+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:25:20.308+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:25:20.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.031 seconds
[2025-02-15T08:25:51.149+0000] {processor.py:186} INFO - Started process (PID=7989) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:25:51.149+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:25:51.151+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:25:51.150+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:25:51.154+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:25:51.153+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:25:51.155+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:25:51.173+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.031 seconds
[2025-02-15T08:25:52.085+0000] {processor.py:186} INFO - Started process (PID=8061) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:25:52.086+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:25:52.087+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:25:52.087+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:25:52.091+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:25:52.090+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:25:52.092+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:25:52.112+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.034 seconds
[2025-02-15T08:25:56.619+0000] {processor.py:186} INFO - Started process (PID=8274) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:25:56.620+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:25:56.621+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:25:56.621+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:25:56.625+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:25:56.624+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:25:56.626+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:25:56.651+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.040 seconds
[2025-02-15T08:26:02.710+0000] {processor.py:186} INFO - Started process (PID=8286) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:02.711+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:26:02.712+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:26:02.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:02.714+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:26:02.713+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:26:02.715+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:02.728+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.022 seconds
[2025-02-15T08:26:08.744+0000] {processor.py:186} INFO - Started process (PID=8298) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:08.745+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:26:08.746+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:26:08.745+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:08.748+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:26:08.748+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:26:08.749+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:08.763+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.023 seconds
[2025-02-15T08:26:11.789+0000] {processor.py:186} INFO - Started process (PID=8303) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:11.790+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:26:11.791+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:26:11.791+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:11.795+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:26:11.794+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:26:11.795+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:11.815+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.030 seconds
[2025-02-15T08:26:39.960+0000] {processor.py:186} INFO - Started process (PID=8609) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:39.961+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:26:39.962+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:26:39.961+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:39.964+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:26:39.963+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:26:39.965+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:39.980+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.024 seconds
[2025-02-15T08:26:42.981+0000] {processor.py:186} INFO - Started process (PID=8614) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:42.982+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:26:42.983+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:26:42.983+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:42.986+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:26:42.985+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:26:42.986+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:43.000+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.025 seconds
[2025-02-15T08:26:44.022+0000] {processor.py:186} INFO - Started process (PID=8619) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:44.022+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:26:44.023+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:26:44.023+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:44.026+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:26:44.025+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:26:44.026+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:44.039+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.022 seconds
[2025-02-15T08:26:47.055+0000] {processor.py:186} INFO - Started process (PID=8624) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:47.055+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:26:47.056+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:26:47.056+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:47.059+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:26:47.058+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:26:47.059+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:47.074+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.023 seconds
[2025-02-15T08:26:49.087+0000] {processor.py:186} INFO - Started process (PID=8629) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:49.088+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:26:49.089+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:26:49.089+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:49.092+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:26:49.091+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:26:49.093+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:49.106+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.023 seconds
[2025-02-15T08:26:51.125+0000] {processor.py:186} INFO - Started process (PID=8634) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:51.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:26:51.128+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:26:51.127+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:51.131+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:26:51.130+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:26:51.132+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:51.148+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.031 seconds
[2025-02-15T08:26:53.356+0000] {processor.py:186} INFO - Started process (PID=8659) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:53.357+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:26:53.358+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:26:53.358+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:53.362+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:26:53.361+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:26:53.363+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:26:53.381+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.030 seconds
[2025-02-15T08:27:07.534+0000] {processor.py:186} INFO - Started process (PID=8945) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:27:07.535+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:27:07.536+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:27:07.536+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:27:07.539+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:27:07.538+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:27:07.539+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:27:07.554+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.024 seconds
[2025-02-15T08:27:12.567+0000] {processor.py:186} INFO - Started process (PID=8950) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:27:12.568+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:27:12.569+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:27:12.568+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:27:12.571+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:27:12.570+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:27:12.572+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:27:12.586+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.023 seconds
[2025-02-15T08:27:42.967+0000] {processor.py:186} INFO - Started process (PID=9256) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:27:42.967+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:27:42.969+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:27:42.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:27:42.971+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:27:42.970+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:27:42.972+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:27:42.985+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.022 seconds
[2025-02-15T08:28:13.299+0000] {processor.py:186} INFO - Started process (PID=9563) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:28:13.300+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:28:13.301+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:28:13.300+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:28:13.303+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:28:13.302+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_tempereture_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:28:13.304+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:28:13.317+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.022 seconds
[2025-02-15T08:28:33.614+0000] {processor.py:186} INFO - Started process (PID=9858) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:28:33.615+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:28:33.617+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:28:33.616+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:28:33.620+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:28:33.619+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_temperature_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:28:33.621+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:28:33.647+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.038 seconds
[2025-02-15T08:29:04.076+0000] {processor.py:186} INFO - Started process (PID=10165) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:29:04.077+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:29:04.077+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:29:04.077+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:29:04.080+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:29:04.079+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_temperature_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:29:04.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:29:04.093+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.023 seconds
[2025-02-15T08:29:34.669+0000] {processor.py:186} INFO - Started process (PID=10415) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:29:34.670+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:29:34.671+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:29:34.670+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:29:34.674+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:29:34.673+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_temperature_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:29:34.675+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:29:34.703+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.042 seconds
[2025-02-15T08:30:05.399+0000] {processor.py:186} INFO - Started process (PID=10692) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:30:05.403+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:30:05.405+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:30:05.404+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:30:05.409+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:30:05.408+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 47
    def _validate_temperature_range()
                                     ^
SyntaxError: expected ':'
[2025-02-15T08:30:05.412+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:30:05.447+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.058 seconds
[2025-02-15T08:30:28.426+0000] {processor.py:186} INFO - Started process (PID=10830) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:30:28.426+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:30:28.428+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:30:28.427+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:30:28.430+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:30:28.430+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 51
    assert data.get("main").get("temp") => 30 and data.get("main").get("temp") <= 45
                                        ^
SyntaxError: invalid syntax
[2025-02-15T08:30:28.431+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:30:28.445+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.024 seconds
[2025-02-15T08:30:58.586+0000] {processor.py:186} INFO - Started process (PID=11135) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:30:58.587+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:30:58.588+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:30:58.588+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:30:58.591+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:30:58.590+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 51
    assert data.get("main").get("temp") => 30 and data.get("main").get("temp") <= 45
                                        ^
SyntaxError: invalid syntax
[2025-02-15T08:30:58.591+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:30:58.605+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.023 seconds
[2025-02-15T08:30:59.597+0000] {processor.py:186} INFO - Started process (PID=11140) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:30:59.598+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:30:59.599+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:30:59.598+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:30:59.601+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:30:59.601+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 51
    assert data.get("main").get("temp") => 30 and data.get("main").get("temp") <= 45
                                        ^
SyntaxError: invalid syntax
[2025-02-15T08:30:59.602+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:30:59.615+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.022 seconds
[2025-02-15T08:31:29.879+0000] {processor.py:186} INFO - Started process (PID=11446) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:31:29.879+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:31:29.880+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:31:29.880+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:31:29.884+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:31:29.883+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 51
    assert data.get("main").get("temp") => 30 and data.get("main").get("temp") <= 45
                                        ^
SyntaxError: invalid syntax
[2025-02-15T08:31:29.885+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:31:29.903+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.030 seconds
[2025-02-15T08:32:00.117+0000] {processor.py:186} INFO - Started process (PID=11752) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:32:00.118+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:32:00.119+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:32:00.119+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:32:00.123+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:32:00.122+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 51
    assert data.get("main").get("temp") => 30 and data.get("main").get("temp") <= 45
                                        ^
SyntaxError: invalid syntax
[2025-02-15T08:32:00.124+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:32:00.143+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.032 seconds
[2025-02-15T08:32:01.140+0000] {processor.py:186} INFO - Started process (PID=11757) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:32:01.141+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:32:01.142+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:32:01.142+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:32:01.157+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:32:01.151+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 138, in <module>
    send_email >> end
    ^^^^^^^^^^
NameError: name 'send_email' is not defined
[2025-02-15T08:32:01.166+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:32:01.185+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.050 seconds
[2025-02-15T08:32:03.485+0000] {processor.py:186} INFO - Started process (PID=11797) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:32:03.486+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:32:03.487+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:32:03.487+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:32:03.491+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:32:03.490+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 51
    assert data.get("main").get("temp") => 30 and data.get("main").get("temp") <= 45
                                        ^
SyntaxError: invalid syntax
[2025-02-15T08:32:03.491+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:32:03.511+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.032 seconds
[2025-02-15T08:32:34.384+0000] {processor.py:186} INFO - Started process (PID=12103) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:32:34.385+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:32:34.386+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:32:34.386+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:32:34.390+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:32:34.389+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 51
    assert data.get("main").get("temp") => 30 and data.get("main").get("temp") <= 45
                                        ^
SyntaxError: invalid syntax
[2025-02-15T08:32:34.391+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:32:34.413+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.034 seconds
[2025-02-15T08:32:50.683+0000] {processor.py:186} INFO - Started process (PID=12340) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:32:50.684+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:32:50.685+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:32:50.684+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:32:50.687+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:32:50.687+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 51
    assert data.get("main").get("temp") => 30 and data.get("main").get("temp") <= 45
                                        ^
SyntaxError: invalid syntax
[2025-02-15T08:32:50.688+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:32:50.704+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.024 seconds
[2025-02-15T08:32:54.709+0000] {processor.py:186} INFO - Started process (PID=12345) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:32:54.710+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:32:54.711+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:32:54.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:32:54.714+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:32:54.713+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 51
    assert data.get("main").get("temp") => 30 and data.get("main").get("temp") <= 45
                                        ^
SyntaxError: invalid syntax
[2025-02-15T08:32:54.714+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:32:54.727+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.023 seconds
[2025-02-15T08:33:20.089+0000] {processor.py:186} INFO - Started process (PID=12652) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:33:20.089+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:33:20.091+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:33:20.091+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:33:20.096+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:33:20.095+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 51
    assert data.get("main").get("temp") => 30 and data.get("main").get("temp") <= 45
                                        ^
SyntaxError: invalid syntax
[2025-02-15T08:33:20.106+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:33:20.140+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.060 seconds
[2025-02-15T08:33:22.128+0000] {processor.py:186} INFO - Started process (PID=12657) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:33:22.129+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:33:22.130+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:33:22.130+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:33:22.133+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:33:22.132+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 51
    assert data.get("main").get("temp") => 30 and data.get("main").get("temp") <= 45
                                        ^
SyntaxError: invalid syntax
[2025-02-15T08:33:22.133+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:33:22.147+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.023 seconds
[2025-02-15T08:33:48.721+0000] {processor.py:186} INFO - Started process (PID=12963) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:33:48.721+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:33:48.722+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:33:48.722+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:33:48.732+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:33:48.729+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 138, in <module>
    send_email >> end
    ^^^^^^^^^^
NameError: name 'send_email' is not defined
[2025-02-15T08:33:48.735+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:33:48.748+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.032 seconds
[2025-02-15T08:33:50.744+0000] {processor.py:186} INFO - Started process (PID=12968) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:33:50.745+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:33:50.746+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:33:50.745+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:33:50.756+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:33:50.753+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 138, in <module>
    send_email >> end
    ^^^^^^^^^^
NameError: name 'send_email' is not defined
[2025-02-15T08:33:50.760+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:33:50.777+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.039 seconds
[2025-02-15T08:33:53.813+0000] {processor.py:186} INFO - Started process (PID=12973) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:33:53.813+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:33:53.815+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:33:53.814+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:33:53.825+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:33:53.822+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 138, in <module>
    send_email >> end
    ^^^^^^^^^^
NameError: name 'send_email' is not defined
[2025-02-15T08:33:53.829+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:33:53.841+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.035 seconds
[2025-02-15T08:33:55.837+0000] {processor.py:186} INFO - Started process (PID=12978) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:33:55.838+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:33:55.839+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:33:55.838+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:33:55.851+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:33:55.848+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 138, in <module>
    send_email >> end
    ^^^^^^^^^^
NameError: name 'send_email' is not defined
[2025-02-15T08:33:55.854+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:33:55.868+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.035 seconds
[2025-02-15T08:34:22.104+0000] {processor.py:186} INFO - Started process (PID=13284) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:34:22.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:34:22.105+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:34:22.105+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:34:22.114+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:34:22.208+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:34:22.208+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:34:22.225+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:34:22.225+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:34:22.240+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.141 seconds
[2025-02-15T08:34:23.273+0000] {processor.py:186} INFO - Started process (PID=13289) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:34:23.273+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:34:23.274+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:34:23.274+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:34:23.283+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:34:23.293+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:34:23.292+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:34:23.313+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:34:23.313+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:34:23.327+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.058 seconds
[2025-02-15T08:34:51.510+0000] {processor.py:186} INFO - Started process (PID=13602) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:34:51.511+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:34:51.512+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:34:51.512+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:34:51.523+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:34:51.531+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:34:51.531+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:34:51.550+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:34:51.550+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:34:51.563+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.059 seconds
[2025-02-15T08:34:55.560+0000] {processor.py:186} INFO - Started process (PID=13607) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:34:55.565+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:34:55.566+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:34:55.566+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:34:55.579+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:34:55.613+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:34:55.612+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:34:55.635+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:34:55.635+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:34:55.649+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.096 seconds
[2025-02-15T08:35:02.993+0000] {processor.py:186} INFO - Started process (PID=13647) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:35:02.993+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:35:02.994+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:35:02.994+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:35:03.003+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:35:03.018+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:35:03.018+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:35:03.036+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:35:03.036+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:35:03.050+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.062 seconds
[2025-02-15T08:35:33.904+0000] {processor.py:186} INFO - Started process (PID=13953) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:35:33.904+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:35:33.905+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:35:33.905+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:35:33.913+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:35:33.928+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:35:33.928+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:35:33.946+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:35:33.946+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:35:33.959+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.061 seconds
[2025-02-15T08:36:00.647+0000] {processor.py:186} INFO - Started process (PID=14231) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:36:00.648+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:36:00.649+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:36:00.649+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:36:00.662+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:36:00.684+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:36:00.683+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:36:00.711+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:36:00.710+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:36:00.728+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.087 seconds
[2025-02-15T08:36:20.518+0000] {processor.py:186} INFO - Started process (PID=14504) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:36:20.519+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:36:20.520+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:36:20.520+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:36:20.528+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:36:20.544+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:36:20.544+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:36:20.562+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:36:20.562+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:36:20.576+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.062 seconds
[2025-02-15T08:36:50.777+0000] {processor.py:186} INFO - Started process (PID=14804) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:36:50.778+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:36:50.779+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:36:50.779+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:36:50.790+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:36:50.812+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:36:50.812+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:36:50.839+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:36:50.839+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:36:50.856+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.085 seconds
[2025-02-15T08:37:21.240+0000] {processor.py:186} INFO - Started process (PID=15114) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:37:21.241+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:37:21.243+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:37:21.243+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:37:21.253+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:37:21.275+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:37:21.275+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:37:21.302+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:37:21.302+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:37:21.318+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.084 seconds
[2025-02-15T08:37:52.040+0000] {processor.py:186} INFO - Started process (PID=15416) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:37:52.041+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:37:52.042+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:37:52.041+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:37:52.052+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:37:52.075+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:37:52.075+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:37:52.102+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:37:52.102+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:37:52.119+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.085 seconds
[2025-02-15T08:38:22.475+0000] {processor.py:186} INFO - Started process (PID=15729) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:38:22.476+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:38:22.477+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:38:22.476+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:38:22.485+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:38:22.501+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:38:22.501+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:38:22.522+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:38:22.522+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:38:22.535+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.064 seconds
[2025-02-15T08:38:52.713+0000] {processor.py:186} INFO - Started process (PID=16035) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:38:52.714+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:38:52.715+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:38:52.715+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:38:52.724+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:38:52.739+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:38:52.739+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:38:52.758+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:38:52.757+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:38:52.770+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.061 seconds
[2025-02-15T08:39:23.372+0000] {processor.py:186} INFO - Started process (PID=16347) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:39:23.372+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:39:23.373+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:39:23.373+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:39:23.380+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:39:23.396+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:39:23.396+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:39:23.416+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:39:23.416+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:39:23.429+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.062 seconds
[2025-02-15T08:39:53.582+0000] {processor.py:186} INFO - Started process (PID=16653) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:39:53.583+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:39:53.584+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:39:53.584+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:39:53.592+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:39:53.607+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:39:53.607+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:39:53.625+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:39:53.625+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:39:53.639+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.061 seconds
[2025-02-15T08:40:23.839+0000] {processor.py:186} INFO - Started process (PID=16966) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:40:23.840+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:40:23.841+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:40:23.841+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:40:23.848+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:40:23.865+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:40:23.865+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:40:23.883+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:40:23.883+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:40:23.897+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.062 seconds
[2025-02-15T08:40:54.230+0000] {processor.py:186} INFO - Started process (PID=17273) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:40:54.231+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:40:54.232+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:40:54.232+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:40:54.240+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:40:54.256+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:40:54.256+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:40:54.274+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:40:54.274+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:40:54.289+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.063 seconds
[2025-02-15T08:41:24.766+0000] {processor.py:186} INFO - Started process (PID=17586) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:41:24.767+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:41:24.767+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:41:24.767+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:41:24.775+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:41:24.791+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:41:24.791+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:41:24.810+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:41:24.810+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:41:24.824+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.063 seconds
[2025-02-15T08:41:54.932+0000] {processor.py:186} INFO - Started process (PID=17892) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:41:54.932+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:41:54.933+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:41:54.933+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:41:54.941+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:41:54.957+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:41:54.957+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:41:54.975+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:41:54.975+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:41:54.989+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.062 seconds
[2025-02-15T08:42:25.164+0000] {processor.py:186} INFO - Started process (PID=18198) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:42:25.165+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:42:25.166+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:42:25.165+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:42:25.173+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:42:25.189+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:42:25.189+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:42:25.208+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:42:25.208+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:42:25.221+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.062 seconds
[2025-02-15T08:42:55.302+0000] {processor.py:186} INFO - Started process (PID=18504) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:42:55.303+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:42:55.304+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:42:55.303+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:42:55.311+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:42:55.327+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:42:55.327+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:42:55.346+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:42:55.346+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:42:55.358+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.061 seconds
[2025-02-15T08:43:07.101+0000] {processor.py:186} INFO - Started process (PID=18524) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:43:07.102+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:43:07.103+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:43:07.102+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:43:07.112+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:43:07.294+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:43:07.294+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:43:07.331+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:43:07.331+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:43:07.364+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.267 seconds
[2025-02-15T08:43:28.407+0000] {processor.py:186} INFO - Started process (PID=18821) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:43:28.408+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:43:28.409+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:43:28.409+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:43:28.418+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:43:28.427+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:43:28.427+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:43:28.462+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:43:28.462+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:43:28.478+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.075 seconds
[2025-02-15T08:43:35.447+0000] {processor.py:186} INFO - Started process (PID=18826) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:43:35.447+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:43:35.448+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:43:35.448+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:43:35.457+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:43:35.466+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:43:35.466+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:43:35.485+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:43:35.485+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:43:35.499+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.056 seconds
[2025-02-15T08:43:37.080+0000] {processor.py:186} INFO - Started process (PID=18841) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:43:37.082+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:43:37.083+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:43:37.083+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:43:37.095+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:43:37.104+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:43:37.104+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:43:37.124+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:43:37.124+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:43:37.137+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.062 seconds
[2025-02-15T08:44:07.952+0000] {processor.py:186} INFO - Started process (PID=19136) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:44:07.953+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:44:07.954+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:44:07.954+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:44:07.967+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:44:07.993+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:44:07.993+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:44:08.020+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:44:08.020+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:44:08.038+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.091 seconds
[2025-02-15T08:44:38.444+0000] {processor.py:186} INFO - Started process (PID=19448) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:44:38.445+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:44:38.445+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:44:38.445+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:44:38.454+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:44:38.480+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:44:38.480+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:44:38.509+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:44:38.509+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:44:38.528+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.088 seconds
[2025-02-15T08:45:09.021+0000] {processor.py:186} INFO - Started process (PID=19754) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:45:09.021+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:45:09.022+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:45:09.022+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:45:09.030+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:45:09.045+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:45:09.045+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:45:09.063+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:45:09.063+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:45:09.075+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.060 seconds
[2025-02-15T08:45:39.448+0000] {processor.py:186} INFO - Started process (PID=20066) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:45:39.449+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:45:39.450+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:45:39.449+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:45:39.457+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:45:39.473+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:45:39.473+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:45:39.492+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:45:39.492+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:45:39.504+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.061 seconds
[2025-02-15T08:46:10.231+0000] {processor.py:186} INFO - Started process (PID=20373) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:46:10.231+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:46:10.232+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:46:10.232+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:46:10.240+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:46:10.265+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:46:10.264+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:46:10.287+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:46:10.287+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:46:10.299+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.073 seconds
[2025-02-15T08:46:40.532+0000] {processor.py:186} INFO - Started process (PID=20685) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:46:40.533+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:46:40.533+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:46:40.533+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:46:40.541+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:46:40.557+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:46:40.557+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:46:40.578+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:46:40.578+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:46:40.591+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.063 seconds
[2025-02-15T08:47:10.973+0000] {processor.py:186} INFO - Started process (PID=20992) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:47:10.974+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:47:10.975+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:47:10.975+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:47:10.982+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:47:10.999+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:47:10.998+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:47:11.017+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:47:11.017+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:47:11.030+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.062 seconds
[2025-02-15T08:47:41.993+0000] {processor.py:186} INFO - Started process (PID=21305) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:47:41.994+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:47:41.995+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:47:41.994+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:47:42.002+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:47:42.018+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:47:42.018+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:47:42.036+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:47:42.036+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:47:42.049+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.060 seconds
[2025-02-15T08:48:12.968+0000] {processor.py:186} INFO - Started process (PID=21611) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:48:12.969+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:48:12.970+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:48:12.970+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:48:12.977+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:48:12.992+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:48:12.992+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:48:13.011+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:48:13.011+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:48:13.023+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.060 seconds
[2025-02-15T08:48:43.245+0000] {processor.py:186} INFO - Started process (PID=21918) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:48:43.246+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:48:43.246+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:48:43.246+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:48:43.254+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:48:43.270+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:48:43.270+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:48:43.290+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:48:43.290+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:48:43.303+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.062 seconds
[2025-02-15T08:49:14.052+0000] {processor.py:186} INFO - Started process (PID=22225) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:49:14.052+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:49:14.053+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:49:14.053+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:49:14.061+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:49:14.077+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:49:14.077+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:49:14.097+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:49:14.096+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:49:14.109+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.062 seconds
[2025-02-15T08:49:44.560+0000] {processor.py:186} INFO - Started process (PID=22532) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:49:44.560+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:49:44.561+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:49:44.561+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:49:44.569+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:49:44.585+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:49:44.585+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:49:44.604+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:49:44.603+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:49:44.616+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.061 seconds
[2025-02-15T08:50:14.748+0000] {processor.py:186} INFO - Started process (PID=22839) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:50:14.748+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:50:14.749+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:50:14.749+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:50:14.757+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:50:14.773+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:50:14.773+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:50:14.792+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:50:14.791+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:50:14.807+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.064 seconds
[2025-02-15T08:50:45.349+0000] {processor.py:186} INFO - Started process (PID=23146) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:50:45.349+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:50:45.350+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:50:45.350+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:50:45.361+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:50:45.382+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:50:45.382+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:50:45.409+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:50:45.409+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:50:45.426+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.083 seconds
[2025-02-15T08:51:15.527+0000] {processor.py:186} INFO - Started process (PID=23453) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:51:15.528+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:51:15.529+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:51:15.529+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:51:15.538+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:51:15.561+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:51:15.561+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:51:15.579+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:51:15.579+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:51:15.592+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.068 seconds
[2025-02-15T08:51:46.123+0000] {processor.py:186} INFO - Started process (PID=23760) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:51:46.124+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:51:46.125+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:51:46.124+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:51:46.132+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:51:46.150+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:51:46.149+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:51:46.168+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:51:46.168+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:51:46.180+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.062 seconds
[2025-02-15T08:52:16.852+0000] {processor.py:186} INFO - Started process (PID=24067) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:52:16.852+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:52:16.853+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:52:16.853+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:52:16.861+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:52:16.877+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:52:16.877+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:52:16.896+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:52:16.896+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:52:16.909+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.062 seconds
[2025-02-15T08:52:47.108+0000] {processor.py:186} INFO - Started process (PID=24374) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:52:47.109+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:52:47.110+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:52:47.109+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:52:47.117+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:52:47.134+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:52:47.134+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:52:47.153+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:52:47.153+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:52:47.165+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.061 seconds
[2025-02-15T08:53:17.898+0000] {processor.py:186} INFO - Started process (PID=24680) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:53:17.899+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:53:17.900+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:53:17.900+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:53:17.909+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:53:17.930+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:53:17.930+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:53:17.948+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:53:17.948+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:53:17.960+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.066 seconds
[2025-02-15T08:53:48.895+0000] {processor.py:186} INFO - Started process (PID=24987) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:53:48.896+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:53:48.897+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:53:48.897+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:53:48.905+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:53:48.920+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:53:48.920+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:53:48.941+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:53:48.941+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:53:48.953+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.062 seconds
[2025-02-15T08:54:19.067+0000] {processor.py:186} INFO - Started process (PID=25294) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:54:19.068+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:54:19.070+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:54:19.069+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:54:19.081+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:54:19.102+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:54:19.102+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:54:19.120+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:54:19.120+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:54:19.132+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.071 seconds
[2025-02-15T08:54:49.269+0000] {processor.py:186} INFO - Started process (PID=25600) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:54:49.270+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:54:49.271+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:54:49.271+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:54:49.280+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:54:49.301+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:54:49.301+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:54:49.321+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:54:49.321+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:54:49.333+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.072 seconds
[2025-02-15T08:55:20.002+0000] {processor.py:186} INFO - Started process (PID=25907) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:55:20.003+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:55:20.005+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:55:20.004+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:55:20.016+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:55:20.039+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:55:20.039+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:55:20.057+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:55:20.057+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:55:20.070+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.072 seconds
[2025-02-15T08:55:50.439+0000] {processor.py:186} INFO - Started process (PID=26213) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:55:50.439+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:55:50.440+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:55:50.440+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:55:50.448+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:55:50.463+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:55:50.463+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:55:50.481+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:55:50.481+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:55:50.493+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.060 seconds
[2025-02-15T08:56:21.398+0000] {processor.py:186} INFO - Started process (PID=26519) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:56:21.400+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:56:21.401+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:56:21.401+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:56:21.418+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:56:21.448+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:56:21.448+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:56:21.474+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:56:21.474+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:56:21.488+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.096 seconds
[2025-02-15T08:56:52.217+0000] {processor.py:186} INFO - Started process (PID=26825) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:56:52.218+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:56:52.219+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:56:52.218+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:56:52.226+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:56:52.241+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:56:52.241+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:56:52.260+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:56:52.260+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:56:52.272+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.060 seconds
[2025-02-15T08:57:22.468+0000] {processor.py:186} INFO - Started process (PID=27131) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:57:22.469+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:57:22.470+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:57:22.469+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:57:22.478+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:57:22.494+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:57:22.494+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:57:22.512+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:57:22.512+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:57:22.525+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.061 seconds
[2025-02-15T08:57:52.746+0000] {processor.py:186} INFO - Started process (PID=27436) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:57:52.746+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:57:52.747+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:57:52.747+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:57:52.755+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:57:52.771+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:57:52.770+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:57:52.789+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:57:52.789+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:57:52.802+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.064 seconds
[2025-02-15T08:58:23.582+0000] {processor.py:186} INFO - Started process (PID=27743) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:58:23.582+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:58:23.583+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:58:23.583+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:58:23.591+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:58:23.606+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:58:23.606+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:58:23.625+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:58:23.625+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:58:23.638+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.061 seconds
[2025-02-15T08:58:53.811+0000] {processor.py:186} INFO - Started process (PID=28050) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:58:53.812+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:58:53.813+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:58:53.813+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:58:53.820+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:58:53.836+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:58:53.835+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:58:53.854+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:58:53.854+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:58:53.866+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.060 seconds
[2025-02-15T08:59:24.062+0000] {processor.py:186} INFO - Started process (PID=28357) to work on /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:59:24.069+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2025-02-15T08:59:24.070+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:59:24.070+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:59:24.080+0000] {processor.py:925} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2025-02-15T08:59:24.113+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:59:24.113+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-15T08:59:24.138+0000] {logging_mixin.py:190} INFO - [2025-02-15T08:59:24.138+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_api_dag to 2025-02-15 06:00:00+00:00, run_after=2025-02-15 09:00:00+00:00
[2025-02-15T08:59:24.161+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.115 seconds
